import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "../components/site-header";
import { SiteFooter } from "../components/site-footer";
import { BackToTop } from "../components/back-to-top";
import { services } from "@/data/services";
import { pageMetadata } from "@/lib/site";

export const metadata: Metadata = pageMetadata({ title: "DevOps Services | Cloud, CI/CD, Kubernetes & Monitoring | Gajan Rajah", description: "Freelance and contract DevOps services covering cloud infrastructure, CI/CD automation, Kubernetes, OpenShift, monitoring, deployment, and production troubleshooting.", path: "/services" });
const engagements = [["Fixed-scope implementation", "A clearly defined infrastructure, deployment, monitoring, or automation task delivered against an agreed scope."], ["Infrastructure or deployment audit", "A review of an existing environment, deployment workflow, or operational configuration with prioritised findings and recommendations."], ["Short-term troubleshooting", "Focused investigation and remediation of a specific infrastructure, deployment, Kubernetes, Linux, or monitoring problem."], ["Ongoing DevOps assistance", "Scheduled support for teams that need recurring infrastructure, automation, deployment, or reliability improvements without a full-time DevOps hire."]];
const process = [["Discovery and requirements", "Define the problem, current environment, constraints, expected outcome, and access requirements."], ["Technical assessment", "Review the existing architecture, deployment process, infrastructure, risks, and operational dependencies."], ["Implementation plan", "Establish the scope, proposed approach, deliverables, assumptions, and validation criteria."], ["Delivery and validation", "Implement the agreed changes, test the result, verify failure paths where appropriate, and confirm the expected outcome."], ["Documentation and handover", "Provide the relevant configuration notes, operational procedures, and recommendations required to maintain the implementation."]];
const boundaries = ["No guaranteed 24/7 managed operations or emergency-response SLA unless explicitly agreed.", "Production changes require an appropriate backup or rollback path.", "Security testing requires written authorisation.", "Client secrets stay out of public repositories, and production credentials are never committed to source control.", "Scope, access, responsibilities, and validation criteria are agreed before implementation."];
const work = [["OpenShift Platform Engineering", "OpenShift · Ceph · Velero · Ansible", "Built resilient cluster environments, backup paths, storage, and operational guardrails for global client workloads."], ["Homelab / gajan.dev", "GKE · GitLab CI · Prometheus · Grafana", "A personal learning platform for running Kubernetes workloads, observability, and cloud delivery experiments."], ["Zelvo", "Docker · GCP · NeonDB · TypeScript", "Receipt-aware expense tracking application deployed with a practical cloud delivery stack."]];

export default function ServicesPage() {
  return <main id="site-top" className="site concept-cloud services-page"><div className="utility"><span className="pulse" /> AVAILABLE FOR SELECTED DEVOPS PROJECTS</div><SiteHeader />
    <section className="services-hero" aria-labelledby="services-title"><p className="eyebrow">DEVOPS SERVICES</p><h1 id="services-title">DevOps and cloud services for reliable application delivery</h1><p>I help small teams and growing products automate deployments, operate cloud infrastructure, improve observability, and resolve production issues.</p><p className="availability-note">Available for selected freelance and contract DevOps projects.</p><div className="hero-actions"><a className="button primary" href="mailto:gajanrajah@protonmail.com?subject=DevOps%20project%20discussion">Discuss your project <span aria-hidden="true">↗</span></a><Link className="button ghost" href="/#work">View selected work <span aria-hidden="true">↓</span></Link></div></section>
    <section className="services-content" aria-labelledby="service-categories"><div className="section-heading"><div><p className="eyebrow">CAPABILITIES</p><h2 id="service-categories">Practical support, scoped to the work.</h2></div></div><div className="service-details">{services.map((service) => <article className="service-detail" key={service.title}><span className="service-icon" aria-hidden="true">{service.icon}</span><div><h3>{service.title}</h3><p>{service.description}</p></div><div><h4>Typical deliverables</h4><ul>{service.deliverables.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>Suitable for</h4><ul>{service.suitableFor.map((item) => <li key={item}>{item}</li>)}</ul><a href="mailto:gajanrajah@protonmail.com?subject=DevOps%20service%20requirement">Discuss this requirement <b aria-hidden="true">→</b></a></div></article>)}</div></section>
    <section className="services-content"><p className="eyebrow">ENGAGEMENTS</p><h2>Engagement options</h2><div className="services-grid compact-grid">{engagements.map(([title, text]) => <article className="service-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="services-content"><p className="eyebrow">PROCESS</p><h2>How the engagement works</h2><ol className="process-list">{process.map(([title, text], index) => <li key={title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section>
    <section className="services-content"><p className="eyebrow">EXPECTATIONS</p><h2>Service boundaries</h2><div className="boundaries"><p>Clear boundaries protect the delivery, access, and operational safety of both sides.</p><ul>{boundaries.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="services-content"><p className="eyebrow">PROOF</p><h2>Relevant work</h2><div className="relevant-work">{work.map(([title, stack, description]) => <Link href="/#work" className="relevant-work-card" key={title}><span>{stack}</span><h3>{title}</h3><p>{description}</p><b>View selected work →</b></Link>)}</div></section>
    <section className="services-final"><p className="eyebrow">START HERE</p><h2>Discuss your infrastructure or deployment requirements</h2><p>Share the current environment, the problem you are trying to solve, and the outcome you need. I will assess whether the work fits my experience and availability.</p><div className="hero-actions"><a className="button primary" href="mailto:gajanrajah@protonmail.com?subject=DevOps%20project%20discussion">Start a conversation <span aria-hidden="true">↗</span></a><Link className="button ghost" href="/#work">View selected projects <span aria-hidden="true">↓</span></Link></div></section><SiteFooter />
  <BackToTop /></main>;
}
