apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: file-share
  namespace: files
  labels:
    app.kubernetes.io/name: file-share
    release: kps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: file-share
  namespaceSelector:
    matchNames:
      - files
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
