apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - valkey.yaml
  - api.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - grafana-dashboard.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
