"use client";

import { useState } from "react";

const projects = [
  { name: "OpenShift Platform Engineering", environment: "PRODUCTION", stack: "OpenShift · Ceph · Velero · Ansible", detail: "Built resilient cluster environments, backup paths, storage, and operational guardrails for global client workloads.", signal: "Platform" },
  { name: "Homelab / gajan.dev", environment: "LAB", stack: "GKE · GitLab CI · Prometheus · Grafana", detail: "A personal learning platform for running Kubernetes workloads, observability, and cloud delivery experiments.", signal: "Observability" },
  { name: "Zelvo", environment: "LIVE", stack: "Docker · GCP · NeonDB · TypeScript", detail: "Receipt-aware expense tracking application deployed with a practical cloud delivery stack.", signal: "Product" },
];

const cases = [
  { title: "Major-version release safety", context: "Production systems required controlled major-version upgrades without losing operational confidence.", response: "Prepared impact analysis, testing steps, release procedures, and documentation before coordinating rollout work.", tools: "Release management · Linux · Documentation", outcome: "A repeatable, reviewable path for production change." },
  { title: "Automation for patching and migrations", context: "Routine maintenance work created long manual execution paths.", response: "Implemented CI/CD workflows and Ansible automation for patching and migration activities.", tools: "Ansible · CI/CD · Bash", outcome: "Execution time reduced from hours to seconds." },
  { title: "OpenShift platform delivery", context: "Internal and client environments needed practical cluster provisioning and resource planning.", response: "Delivered single-node, multi-node, on-premises, and K3s/OpenShift proof-of-concept environments.", tools: "OpenShift · Kubernetes · VMware", outcome: "Validated platform modules and modernization approaches before rollout." },
  { title: "Observability from the cluster out", context: "Teams needed quicker visibility into service and infrastructure health.", response: "Configured Prometheus, Grafana, exporters, automated health checks, log management, and image-pruning scripts.", tools: "Prometheus · Grafana · Python · Bash", outcome: "A clearer operational signal for systems and data services." },
  { title: "Backup and recovery design", context: "Cluster, namespace, and database workloads required durable recovery procedures.", response: "Automated backups and formed disaster-recovery strategies across clusters and databases.", tools: "Velero · MinIO · MySQL · YugabyteDB", outcome: "Recovery paths documented alongside day-to-day operations." },
  { title: "Network and access hardening", context: "Distributed systems and telco workloads needed secure, reliable access boundaries.", response: "Managed network policies, routes, DNS, HAProxy, and access configuration across OpenShift and product environments.", tools: "NetworkPolicy · HAProxy · DNS · RHEL", outcome: "Stronger access control and clearer service connectivity." },
];

const skills = ["Kubernetes", "OpenShift", "Docker", "GitOps", "CI/CD", "Ansible", "Prometheus", "Grafana", "AWS", "GCP", "Linux", "Python", "Bash", "Ceph", "Velero"];

function OperationsArchitecture() {
  return <div className="operations-architecture" aria-hidden="true"><svg className="ops-map ops-desktop" viewBox="0 0 720 540">
    <g className="ops-zone"><rect x="24" y="42" width="210" height="160" rx="14" /><text x="44" y="69">DELIVERY</text></g><g className="ops-zone"><rect x="270" y="42" width="426" height="230" rx="14" /><text x="290" y="69">PRODUCTION CLUSTER</text></g><g className="ops-zone"><rect x="24" y="316" width="300" height="190" rx="14" /><text x="44" y="343">DATA</text></g><g className="ops-zone"><rect x="360" y="316" width="336" height="190" rx="14" /><text x="380" y="343">OPERATIONS</text></g>
    <g className="ops-links"><path className="deploy-path" d="M150 165H234" /><path className="request-path" d="M483 140V182H396M483 140V182H570" /><path className="data-path" d="M396 226V288H324M570 226V302H324" /><path className="ops-path" d="M650 272V316M324 410H360" /></g>
    <g className="ops-node"><rect x="58" y="95" width="116" height="42" rx="7" /><text x="116" y="121">GIT + CI/CD</text></g><g className="ops-node deploy"><rect x="58" y="151" width="92" height="32" rx="7" /><text x="104" y="172">DEPLOY</text></g><g className="ops-node edge"><rect x="427" y="94" width="112" height="42" rx="7" /><text x="483" y="120">INGRESS</text></g>
    <g className="app-symbol"><path d="M396 175l24 14v28l-24 14-24-14v-28z" /><text x="396" y="250">APP A</text></g><g className="app-symbol"><path d="M570 175l24 14v28l-24 14-24-14v-28z" /><text x="570" y="250">APP B</text></g>
    <g className="database-symbol"><ellipse cx="112" cy="391" rx="31" ry="10" /><path d="M81 391v38c0 6 14 10 31 10s31-4 31-10v-38" /><ellipse cx="112" cy="429" rx="31" ry="10" /><text x="112" y="465">POSTGRES</text></g><g className="database-symbol mongo"><ellipse cx="236" cy="391" rx="31" ry="10" /><path d="M205 391v38c0 6 14 10 31 10s31-4 31-10v-38" /><ellipse cx="236" cy="429" rx="31" ry="10" /><text x="236" y="465">MONGODB</text></g>
    <g className="ops-symbol backup"><path d="M430 385h54v48h-54zM430 385l27-16 27 16" /><text x="457" y="465">BACKUPS</text></g><g className="ops-symbol metric"><path d="M585 433v-38M600 433v-57M615 433v-27M580 433h42" /><text x="601" y="465">METRICS</text></g>
    <circle className="ops-pulse deploy-pulse" r="4"><animateMotion dur="6s" repeatCount="indefinite" path="M104 165H234" /></circle><circle className="ops-pulse request-pulse" r="4"><animateMotion dur="7s" begin="-2s" repeatCount="indefinite" path="M483 115V200H570" /></circle><circle className="ops-pulse backup-pulse" r="4"><animateMotion dur="8s" begin="-4s" repeatCount="indefinite" path="M324 410H360" /></circle>
  </svg><svg className="ops-map ops-mobile" viewBox="0 0 340 620"><g className="ops-zone"><rect x="22" y="22" width="296" height="104" rx="14" /><text x="40" y="49">DELIVERY</text></g><g className="ops-zone"><rect x="22" y="154" width="296" height="174" rx="14" /><text x="40" y="181">PRODUCTION CLUSTER</text></g><g className="ops-zone"><rect x="22" y="356" width="140" height="190" rx="14" /><text x="40" y="383">DATA</text></g><g className="ops-zone"><rect x="178" y="356" width="140" height="190" rx="14" /><text x="196" y="383">OPS</text></g><g className="ops-links"><path className="deploy-path" d="M170 99V126" /><path className="request-path" d="M170 214V254H100M170 214V254H240" /><path className="data-path" d="M100 282V342H162M240 282V332H162" /><path className="ops-path" d="M170 328V356M162 451H178" /></g><g className="ops-node"><rect x="108" y="60" width="124" height="34" rx="7" /><text x="170" y="82">GIT + CI/CD</text></g><g className="ops-node deploy"><rect x="126" y="98" width="88" height="22" rx="6" /><text x="170" y="113">DEPLOY</text></g><g className="ops-node edge"><rect x="120" y="194" width="100" height="34" rx="7" /><text x="170" y="216">INGRESS</text></g><g className="app-symbol"><path d="M100 244l17 10v20l-17 10-17-10v-20z" /><text x="100" y="307">APP A</text></g><g className="app-symbol"><path d="M240 244l17 10v20l-17 10-17-10v-20z" /><text x="240" y="307">APP B</text></g><g className="database-symbol"><ellipse cx="70" cy="440" rx="25" ry="8" /><path d="M45 440v29c0 5 11 8 25 8s25-3 25-8v-29" /><ellipse cx="70" cy="469" rx="25" ry="8" /><text x="70" y="500">POSTGRES</text></g><g className="database-symbol mongo"><ellipse cx="120" cy="440" rx="25" ry="8" /><path d="M95 440v29c0 5 11 8 25 8s25-3 25-8v-29" /><ellipse cx="120" cy="469" rx="25" ry="8" /><text x="120" y="500">MONGO</text></g><g className="ops-symbol backup"><path d="M206 438h36v34h-36zM206 438l18-11 18 11" /><text x="224" y="500">BACKUP</text></g><g className="ops-symbol metric"><path d="M278 472v-28M289 472v-42M300 472v-20M274 472h30" /><text x="289" y="500">METRICS</text></g><circle className="ops-pulse deploy-pulse" r="3"><animateMotion dur="6s" repeatCount="indefinite" path="M170 109V126" /></circle><circle className="ops-pulse request-pulse" r="3"><animateMotion dur="7s" begin="-2s" repeatCount="indefinite" path="M170 210V264H240" /></circle><circle className="ops-pulse backup-pulse" r="3"><animateMotion dur="8s" begin="-4s" repeatCount="indefinite" path="M162 451H178" /></circle></svg></div>;
}

export default function Home() {
  const [resumeMessage, setResumeMessage] = useState(false);

  return <main className="site">
    <div className="utility"><span className="pulse" /> AVAILABLE FOR DEVOPS & SYSTEMS ENGINEERING <b>·</b> REMOTE / HYBRID <b>·</b> COLOMBO / KANDY</div>
    <header className="nav">
      <nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#cases">Case studies</a><a href="#about">Experience</a><a href="#writing">Writing</a></nav>
      <div className="header-actions"><a className="linkedin-link" href="http://www.linkedin.com/in/gajanrajah" target="_blank" rel="noreferrer">LinkedIn <span>↗</span></a><a className="contact-link" href="mailto:gajanrajah@protonmail.com">Contact <span>↗</span></a></div>
    </header>

    <section id="top" className="hero">
      <div className="hero-copy"><p className="eyebrow">DEVOPS / CLOUD ENGINEER</p><h1>Systems, made <em>legible.</em></h1><p className="lede">Gajan Rajah designs, automates, and operates cloud platforms—from resilient OpenShift environments to calmer, more observable delivery workflows.</p><div className="hero-actions"><a className="button primary" href="#work">Explore selected work <span>↓</span></a><button className="button ghost" onClick={() => setResumeMessage(true)}>Resume <span>↗</span></button></div>{resumeMessage && <p className="resume-note">Resume available on request. <a href="mailto:gajanrajah@protonmail.com?subject=Resume%20request">Email Gajan</a>.</p>}</div>
      <div className="hero-system"><div className="system-title"><span className="status"><i /> OPERATIONS OVERVIEW</span></div><OperationsArchitecture /></div>
    </section>

    <section id="work" className="section projects"><div className="section-heading"><p className="eyebrow">SELECTED DEPLOYMENTS</p><h2>Work that holds up<br />when it matters.</h2></div><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.name}><div className="card-top"><span>{String(index + 1).padStart(2,"0")}</span><span className="status"><i /> {project.environment}</span></div><h3>{project.name}</h3><p>{project.detail}</p><footer><span>{project.signal}</span><code>{project.stack}</code></footer></article>)}</div></section>

    <section id="cases" className="section case-section"><div className="section-heading"><p className="eyebrow">PRODUCTION TROUBLESHOOTING</p><h2>Prepared beats<br />heroic.</h2></div><div className="case-panel" tabIndex={0} aria-label="Scrollable production troubleshooting case studies"><div className="case-panel-intro"><p className="eyebrow">FIELD RECORDS</p><h3>Operational decisions, captured in context.</h3><p>Scroll through CV-derived examples of reliability, recovery, automation, and platform work.</p><span className="scroll-cue">SCROLL TO EXPLORE ↓</span></div><div className="case-list">{cases.map((item, index) => <article key={item.title}><span>0{index + 1}</span><div><h3>{item.title}</h3><dl><div><dt>Context</dt><dd>{item.context}</dd></div><div><dt>Response</dt><dd>{item.response}</dd></div><div><dt>Tools</dt><dd>{item.tools}</dd></div><div><dt>Outcome</dt><dd>{item.outcome}</dd></div></dl></div></article>)}</div></div></section>

    <section id="about" className="section experience"><div><p className="eyebrow">EXPERIENCE</p><h2>Four years of<br />systems thinking.</h2></div><div className="timeline"><article><span>2026 — NOW</span><h3>DevOps / Systems Engineer</h3><p>hSenid Mobile Solutions</p></article><article><span>2024 — 2026</span><h3>Associate DevOps / Cloud Engineer</h3><p>hSenid Mobile Solutions</p></article><article><span>2021 — 2024</span><h3>DevOps & Backend Engineering</h3><p>hSenid Mobile Solutions · appiGo · IntendAble</p></article></div></section>

    <section className="section capability-grid"><article><p className="eyebrow">OPERATING STACK</p><div className="skill-cloud">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></article><article><p className="eyebrow">CERTIFICATIONS</p><ul><li>Red Hat Certified OpenShift Administrator <span>2025</span></li><li>Red Hat System Administration I <span>2025</span></li><li>Containers & Kubernetes Essentials <span>2024</span></li><li>AWS Educate: Cloud 101 <span>2023</span></li></ul></article></section>

    <section id="writing" className="section writing"><div><p className="eyebrow">TECHNICAL WRITING</p><h2>Make operations<br />repeatable.</h2></div><div className="writing-card"><span>FIELD NOTE / 001</span><h3>Operational docs that shorten the path from alert to action.</h3><p>Procedure writing, knowledge transfer, deployment notes, and impact analysis are part of the system—not an afterthought.</p><a href="mailto:gajanrajah@protonmail.com?subject=Technical%20writing">Request a writing sample →</a></div></section>

    <footer className="footer"><div><p className="eyebrow">NEXT DEPLOYMENT</p><h2>Let’s make your<br /><em>platform calmer.</em></h2></div><a className="button primary" href="mailto:gajanrajah@protonmail.com">Start a conversation <span>↗</span></a><small>© 2026 Gajan Rajah · Built as a private portfolio prototype</small></footer>
  </main>;
}
