import type { Article } from "../types/article.ts";

// Verified from https://trikto.medium.com/feed on 2026-07-16.
export const fallbackArticles: Article[] = [
  {
    title: "CI/CD Pipelines Explained in Simple Terms",
    description: "Most people working in tech have heard of CI/CD pipelines, but beginners often see them as some kind of DevOps magic. A developer pushes code, tests run automatically, and the application is deployed.",
    url: "https://trikto.medium.com/ci-cd-pipelines-explained-in-simple-terms-dbe44f01c4c7",
    slug: "ci-cd-pipelines-explained-in-simple-terms-dbe44f01c4c7",
    image: "https://cdn-images-1.medium.com/max/1024/1*8bZ806dfZJuQHFICW8Jgqg.png",
    publishedAt: "2026-07-15T17:38:47.000Z",
    readingTime: "6 min read",
    categories: ["ci-cd-pipeline", "github-actions", "devops", "gitlab"],
  },
  {
    title: "What is the meaning of life? A new perspective to start living…",
    description: "A new perspective on the meaning of life, how we choose to live, and the ideas that can help us make those choices deliberately.",
    url: "https://trikto.medium.com/what-is-the-meaning-of-life-a-new-perspective-to-start-living-62dd1434ae57",
    slug: "what-is-the-meaning-of-life-a-new-perspective-to-start-living-62dd1434ae57",
    image: "https://cdn-images-1.medium.com/max/1024/0*aRu6Ryn57nrdinZc",
    publishedAt: "2026-01-04T15:45:22.000Z",
    readingTime: "3 min read",
    categories: ["stoicism", "philosophy", "life"],
  },
  {
    title: "How to setup Nginx to host your website?",
    description: "A practical guide to installing Nginx with a package manager and configuring the lightweight web server to host a website.",
    url: "https://trikto.medium.com/how-to-setup-nginx-to-host-your-website-38ea7db1b58d",
    slug: "how-to-setup-nginx-to-host-your-website-38ea7db1b58d",
    image: "https://cdn-images-1.medium.com/max/800/1*iTGAA9Gvyqh5TirEnhnhgA.png",
    publishedAt: "2026-01-03T17:27:01.000Z",
    readingTime: "2 min read",
    categories: ["nginx", "linux"],
  },
  {
    title: "How to setup SSH?",
    description: "A concise guide to generating an SSH key pair and setting up secure remote connections to other machines.",
    url: "https://trikto.medium.com/how-to-setup-ssh-b4281bf7704b",
    slug: "how-to-setup-ssh-b4281bf7704b",
    image: "https://cdn-images-1.medium.com/max/1024/1*2Ju2YURlVsjtdpsnlib69Q.png",
    publishedAt: "2026-01-03T12:52:57.000Z",
    readingTime: "1 min read",
    categories: ["linux", "ssh"],
  },
  {
    title: "Cloning docker images between repositories without downloading them",
    description: "Use Skopeo to copy container images between repositories without first downloading them to a local machine.",
    url: "https://trikto.medium.com/cloning-docker-images-between-repositories-without-downloading-them-413a636536ce",
    slug: "cloning-docker-images-between-repositories-without-downloading-them-413a636536ce",
    image: "https://cdn-images-1.medium.com/max/930/1*0b8Le6jRk25rGkPg9j67Kg.png",
    publishedAt: "2025-12-28T08:36:23.000Z",
    readingTime: "1 min read",
    categories: ["skopeo", "gitlab", "docker", "containers", "ci-cd-pipeline"],
  },
  {
    title: "What is GitOps and why do you need it?",
    description: "An introduction to GitOps, its relationship to infrastructure as code, and why it improves cloud and Kubernetes operations.",
    url: "https://trikto.medium.com/what-is-gitops-and-why-do-you-need-it-a9a42f187497",
    slug: "what-is-gitops-and-why-do-you-need-it-a9a42f187497",
    image: "https://cdn-images-1.medium.com/max/1024/1*Jjj8hwWWowjQczUADMn6aQ.png",
    publishedAt: "2025-12-26T08:52:28.000Z",
    readingTime: "3 min read",
    categories: ["kubernetes", "devops", "gitops", "cloud-computing", "git"],
  },
  {
    title: "TakeOver Room in TryHackMe",
    description: "A practical TryHackMe walkthrough covering subdomain enumeration and the steps used to complete the TakeOver room.",
    url: "https://infosecwriteups.com/takeover-room-in-tryhackme-23c045bb3644",
    slug: "takeover-room-in-tryhackme-23c045bb3644",
    image: "https://cdn-images-1.medium.com/max/512/1*qRw1FCLyUswIjyYLriCjjA.png",
    publishedAt: "2025-11-21T15:38:19.000Z",
    readingTime: "1 min read",
    categories: ["tryhackme-writeup", "enumeration", "tryhackme", "subdomain", "ctf-writeup"],
  },
  {
    title: "W1seGuy Room in TryHackMe",
    description: "A concise TryHackMe walkthrough examining the supplied source code, XOR behavior, encryption, and reverse-engineering path.",
    url: "https://infosecwriteups.com/w1seguy-room-in-tryhackme-031880e5a138",
    slug: "w1seguy-room-in-tryhackme-031880e5a138",
    image: "https://cdn-images-1.medium.com/max/1024/1*jzR9LAbzyis6Ky6tE-crzA.png",
    publishedAt: "2025-11-19T17:49:19.000Z",
    readingTime: "3 min read",
    categories: ["tryhackme-writeup", "reverse-engineering", "tryhackme", "encryption"],
  },
  {
    title: "How to setup a HA K3s cluster in a homelab?",
    description: "Build a highly available K3s homelab cluster with three master nodes and five worker nodes running as containers in a local VM.",
    url: "https://trikto.medium.com/how-to-setup-a-ha-k3s-cluster-in-a-homelab-03d9761cc9e2",
    slug: "how-to-setup-a-ha-k3s-cluster-in-a-homelab-03d9761cc9e2",
    image: "https://cdn-images-1.medium.com/max/710/1*AfzGV9gApynRrhbMokGkaA.png",
    publishedAt: "2025-10-27T15:28:42.000Z",
    readingTime: "2 min read",
    categories: ["kubernetes", "docker", "containers", "k3d", "homelab"],
  },
  {
    title: "How to move/migrate Steam games from one PC to another",
    description: "Move existing Steam games to a new or upgraded PC without downloading the full game library again.",
    url: "https://trikto.medium.com/how-to-move-migrate-steam-games-from-one-pc-to-another-39d09dd1dfa9",
    slug: "how-to-move-migrate-steam-games-from-one-pc-to-another-39d09dd1dfa9",
    image: "https://cdn-images-1.medium.com/max/300/1*2JPGemOdZO36uzS92EEUCg.jpeg",
    publishedAt: "2025-04-15T05:56:44.000Z",
    readingTime: "3 min read",
    categories: ["mortal-kombat-11", "steam", "games"],
  },
];
